### ISSUE TITLE
Can no longer compare arrays in version 0.5.6

### ISSUE THREAD

**Issue by nataelbaffou** [jwiegley/comparable#13]
## Version 
From 0.5.5 to 0.5.6

## Description
I was able to compare native arrays in version 0.5.5 but they no longer have the Comparable trait satisfied in 0.5.6

## Reproduction
```rust
use comparable::*;

fn main() {
    let t1 = [0u8; 5];
    let t2 = [0u8; 5];
    assert_changes!(&t1, &t2, Changed::Unchanged);
    print!("{:?}", t1.comparison(&t2));
}
```

This builds, run and works in 0.5.5

In 0.5.6 we have the following errors:
```
for assert_changes!(&t1... => error[E0599]: the method `comparison` exists for reference `&[u8; 5]`, but its trait bounds were not satisfied
for t1.comparison(&t2... => error[E0599]: no method named `comparison` found for array `[u8; 5]` in the current scope
```

## Expected behaviour
Same as in 0.5.5, or is there an easy workaround that does not mean using a vec instead of an array ?
